module.exports = {
  // Auth actions
  USERNAME: 'USERNAME',
  PASSWORD: 'PASSWORD',
  AUTH_SUBMIT: 'SIGN_IN_SUBMIT',
  AUTH_SUCCESS: 'SIGN_IN_SUCCESS',
  AUTH_FAILURE: 'SIGN_IN_FAILURE',


  // Survey actions
  SURVEY_SUBMIT: 'SURVEY_SUBMIT',
  SURVEY_SUCCESS: 'SURVEY_SUCCESS',
  SURVEY_FAILURE: 'SURVEY_FAILURE',
  FEELING_CHANGE: 'FEELING_CHANGE',
  ANXIETY_CHANGE: 'ANXIETY_CHANGE',
  SLEEP_CHANGE: 'SLEEP_CHANGE',
  MOOD_CHANGE: 'MOOD_CHANGE',
  MAJOR_EVENT_CHANGE: 'MAJOR_EVENT_CHANGE',
  EVENT_ELABORATE_CHANGE: 'EVENT_ELABORATE_CHANGE',
  ENERGY_CHANGE: 'ENERGY_CHANGE',
  SLEEP_ELABORATE_CHANGE: 'SLEEP_ELABORATE_CHANGE',
  MOOD_ELABORATE_CHANGE: 'MOOD_ELABORATE_CHANGE'
};
